drop table if EXISTS logs;
CREATE TABLE logs(
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL ,
  time VARCHAR(255) NOT NULL ,
  status VARCHAR(255) NOT NULL ,
  message text NOT NULL
)CHARACTER SET utf8mb4 ENGINE innodb;